"use strict";

var gulp = require("gulp");
var plumber = require("gulp-plumber");
var rigger = require("gulp-rigger");
var htmlmin = require("gulp-htmlmin");
var server = require("browser-sync").create();

gulp.task("htmlbuild", function() {
  return gulp.src("source/template/*.html")
    .pipe(plumber())
    .pipe(rigger())
    .pipe(gulp.dest("build/before"))
    .pipe(htmlmin({
      html5: true,
      useShortDoctype: false,
      includeAutoGeneratedTags: false,
      keepClosingSlash: false,
      preventAttributesEscaping: true,
      decodeEntities: false,
      caseSensitive: false,
      processConditionalComments: true,
      removeComments: true,
      collapseBooleanAttributes: true,
      collapseWhitespace: true,
      collapseInlineTagWhitespace: false,
      conservativeCollapse: false,
      preserveLineBreaks: false,
      removeOptionalTags: false,
      removeEmptyElements: true,
      removeAttributeQuotes: true,
      removeEmptyAttributes: false,
      removeRedundantAttributes: true,
      removeStyleLinkTypeAttributes: true,
      minifyCSS: true,
      removeScriptTypeAttributes: true,
      minifyJS: true,
      removeTagWhitespace: false,
      sortAttributes: false,
      sortClassName: false
    }))
    .pipe(gulp.dest("build/after"))
    .pipe(server.stream());
});

gulp.task("server", function () {
  server.init({
    server: "build/after",
    notify: false,
    open: true,
    cors: true,
    ui: false
  });

  gulp.watch("source/template/**/*.html", gulp.series("htmlbuild"));
  gulp.watch("build/after*.html").on("change", server.reload);
});

gulp.task("copy", function(done) {
  gulp.src("build/after/*.html").pipe(gulp.dest("public/"));
  done();
});

gulp.task("start", gulp.series("htmlbuild", "server"));
gulp.task("public", gulp.series("htmlbuild", "copy"));
